spring.application.name=civic-issue-management

spring.datasource.url=jdbc:mysql://localhost:3306/civic_issue_management
spring.datasource.username=root
spring.datasource.password=SHerin@05.******

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
